Update location of handlers to that make_min_web2py.py works again
The location of the handlers changed in 07f74c63621 and since then
this error blocked the creation of a minizimed web2py instance:

IOError: [Errno 2] No such file or directory: 'fcgihandler.py'